package Presentacion;

import Logica.conexion;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class catalogo extends javax.swing.JFrame {

    // Se instancia una conexion de la clase conecta
    conexion con = new conexion();
    // se asigna la conexion a la base de datos con la variable cn
    Connection cn = con.conectar();
    // asignamos la primera tabla
    DefaultTableModel manipulacion;

    public catalogo() {
        initComponents();
        this.setLocationRelativeTo(null);
        asignarAutocompletado();
        asignarAutocompletadoMaquila();
        btnIntegrar.setEnabled(false);
        btnImagen.setEnabled(false);
    }

    public void asignarAutocompletado() {
        TextAutoCompleter textAutoCompleter = new TextAutoCompleter(txtPredecible);
        textAutoCompleter.setMode(0); // infijo
        textAutoCompleter.setCaseSensitive(false); //No sensible a mayúsculas

        //iniciamos
        try {
            String sql = "SELECT * FROM inventario";
            Statement completar;
            completar = cn.createStatement();
            ResultSet rs = completar.executeQuery(sql);
            while (rs.next()) {
                textAutoCompleter.addItem(rs.getString("nombre"));

            }

        } catch (SQLException ex) {
            System.out.println("Sin poder ejecutar el query a la tabla");
        }

    }

    public void asignarAutocompletadoMaquila() {
        TextAutoCompleter textAutoCompleter = new TextAutoCompleter(txtMaquila);
        textAutoCompleter.setMode(0); // infijo
        textAutoCompleter.setCaseSensitive(false); //No sensible a mayúsculas

        //iniciamos
        try {
            String sql = "SELECT * FROM maquila";
            Statement completar;
            completar = cn.createStatement();
            ResultSet rs = completar.executeQuery(sql);
            while (rs.next()) {
                textAutoCompleter.addItem(rs.getString("nombre"));

            }

        } catch (SQLException ex) {
            System.out.println("Sin poder ejecutar el query a la tabla");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLinea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtArticulo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        chkActivo = new javax.swing.JCheckBox();
        panel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtPredecible = new javax.swing.JTextField();
        btnIntegrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMan = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSubManipulacion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMaquila = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPrecio1 = new javax.swing.JTextField();
        btnActMaquila = new javax.swing.JButton();
        btnNuevaMaquila = new javax.swing.JButton();
        btnActInventario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Catalogo"));

        jLabel1.setText("Linea");

        jLabel2.setText("Modelo");

        jLabel3.setText("Articulo");

        jLabel4.setText("Color");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/editar.png"))); // NOI18N
        btnEditar.setText("Editar");

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/nuevo.png"))); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        chkActivo.setSelected(true);
        chkActivo.setText("Activo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(chkActivo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrear)
                    .addComponent(btnEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(chkActivo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Especificacion");

        btnIntegrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/grabar.png"))); // NOI18N
        btnIntegrar.setText("Integrar");
        btnIntegrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntegrarActionPerformed(evt);
            }
        });

        tablaMan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Material", "Unidad", "Consumo", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablaMan);

        btnBorrar.setText("Borrar");

        btnActualizar.setText("Actualizar");

        jLabel6.setText("Consumo por par");

        jLabel7.setText("Precio");

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel10.setText("SubTotal");

        jLabel11.setText("Maquila");

        jLabel13.setText("Costo");

        txtPrecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecio1ActionPerformed(evt);
            }
        });

        btnActMaquila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/actmaquila.png"))); // NOI18N
        btnActMaquila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActMaquilaActionPerformed(evt);
            }
        });

        btnNuevaMaquila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/maquila.png"))); // NOI18N
        btnNuevaMaquila.setText("Nuevo");
        btnNuevaMaquila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaMaquilaActionPerformed(evt);
            }
        });

        btnActInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/actmaquila.png"))); // NOI18N
        btnActInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addGap(39, 39, 39)
                                .addComponent(btnBorrar)
                                .addGap(435, 435, 435)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(txtSubManipulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPredecible, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtMaquila))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActMaquila, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnActInventario)
                                .addGap(0, 1, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnNuevaMaquila))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntegrar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIntegrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtPredecible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnActInventario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtMaquila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnActMaquila)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevaMaquila)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnActualizar)
                    .addComponent(jLabel10)
                    .addComponent(txtSubManipulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel.addTab("Manipulacion", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        panel.addTab("Costura-Pespunte", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        panel.addTab("Inyeccion y Terminacion", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        panel.addTab("Total", jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        btnImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/imagen.png"))); // NOI18N
        btnImagen.setText("Actualizar Imagen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIntegrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntegrarActionPerformed
        //verificamos si es maquila o inventario a integrar el modelo

        //checamos que no tengan ambos campos con texto
        if (txtPredecible.getText().length() > 1 && txtMaquila.getText().length() > 1) {
            JOptionPane.showMessageDialog(this, "Solo integra un elemento a la vez");
        } // vericamos que ambos no esten vacios
        else if (txtPredecible.getText().length() == 0 && txtMaquila.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Agrega un material o una maquila");
        } else if (txtPredecible.getText().length() > 1) {
            //aqui integramos un material del inventario

            //primero verificamos que si este en la base de datos de inventario
            int contador = 0;
            try {
                String checar = "SELECT * FROM inventario WHERE nombre='" + txtPredecible.getText() + "'";
                Statement repetido;
                repetido = cn.createStatement();
                ResultSet buscar = repetido.executeQuery(checar);
                while (buscar.next()) {
                    contador = 1;

                }
            } catch (SQLException ex) {
                Logger.getLogger(frminventario.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (contador == 1) {
                //revisamos que no este repetido el material en el calzado

                int material = 0;
                try {
                    String checar = "SELECT * FROM calzado WHERE nombre='" + txtPredecible.getText() + "' and modelo='"
                            + txtModelo.getText() + "' and articulo='" + txtArticulo.getText() + "'";
                    Statement repetido;
                    repetido = cn.createStatement();
                    ResultSet buscar = repetido.executeQuery(checar);
                    while (buscar.next()) {
                        material++;
                        JOptionPane.showMessageDialog(this, "El material ya esta en la hoja de especificacion");

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(frminventario.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (material == 0) {
                    // como si existe el material en la bd de datos de inventario, procedemos a integrarlo a Calzado
                    if (txtPar.getText().length() == 0) {
                        JOptionPane.showMessageDialog(this, "Falta agregar el costo");
                    } else if (txtPrecio.getText().length() == 0) {
                        JOptionPane.showMessageDialog(this, "Falta agregar el Precio");
                    } else {
                        //Asignamos variables a la especificacion
                        String Linea = txtLinea.getText().toUpperCase();
                        String Modelo = txtModelo.getText().toUpperCase();
                        String Articulo = txtArticulo.getText().toUpperCase();
                        String Color = txtColor.getText().toUpperCase();
                        String Nombre = txtPredecible.getText();
                        String Consumo = txtPar.getText();
                        String Precio = txtPrecio.getText();
                        String Codigo = null;
                        String Pieza = null;
                        String Medida = null;
                        String Activo = "1";
                        //calculamos el costo
                        String txtResultado = redondeo();
                        // verificamos si esta seleccionado
                        if (!chkActivo.isSelected()) {
                            Activo = "0";
                        }
                        String sql = "SELECT * FROM inventario WHERE nombre='" + txtPredecible.getText() + "'";

                        //buscamos en la base de datos Inventario las especificaciones faltantes
                        try {
                            Statement completar;
                            completar = cn.createStatement();
                            ResultSet rs = completar.executeQuery(sql);
                            while (rs.next()) {
                                Codigo = rs.getString("codigo");
                                Pieza = rs.getString("pieza");
                                Medida = rs.getString("medida");
                            }
                        } catch (SQLException ex) {
                            System.out.println("Sin poder ejecutar el query para asignar valores");
                        }

                        //ya teniendo todos los valores integramos la especificacion a la BD calzado
                        try {
                            Statement stmt = cn.createStatement();
                            String grabar = "INSERT INTO calzado (modelo,codigo,linea,articulo,color,pieza,nombre,medida,consumo,precio,resultado,estado,proceso) "
                                    + "VALUES ('"
                                    + Modelo + "','"
                                    + Codigo + "','"
                                    + Linea + "','"
                                    + Articulo + "','"
                                    + Color + "','"
                                    + Pieza + "','"
                                    + Nombre + "','"
                                    + Medida + "','"
                                    + Consumo + "','"
                                    + Precio + "','"
                                    + txtResultado + "','"
                                    + Activo + "','manipulacion');";
                            stmt.executeUpdate(grabar);

                            stmt.close();
                            txtSubManipulacion.setText("0.00");
                            mostrarTabla();
                        } catch (SQLException ex) {
                            Logger.getLogger(frminventario.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                    
                }
            }if (contador == 0) {
                        JOptionPane.showMessageDialog(this, "No modifiques la ventana de materiales");
                        txtPredecible.setText("");
                        txtPar.setText("");
                        txtPrecio.setText("");
                    }
        } else if (txtMaquila.getText().length()>0){
            // ********** Inicia Captura de Maquila
            
            
            //primero verificamos que si este en la base de datos de maquila
            int contador = 0;
            try {
                String checar = "SELECT * FROM maquila WHERE nombre='" + txtMaquila.getText() + "'";
                Statement repetido;
                repetido = cn.createStatement();
                ResultSet buscar = repetido.executeQuery(checar);
                while (buscar.next()) {
                    contador = 1;

                }
            } catch (SQLException ex) {
                Logger.getLogger(frminventario.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (contador == 1) {
                //revisamos que no este repetido la maquila en el calzado

                int material = 0;
                try {
                    String checar = "SELECT * FROM calzado WHERE nombre='" + txtMaquila.getText() + "' and modelo='"
                            + txtModelo.getText() + "' and articulo='" + txtArticulo.getText() + "'";
                    Statement repetido;
                    repetido = cn.createStatement();
                    ResultSet buscar = repetido.executeQuery(checar);
                    while (buscar.next()) {
                        material++;
                        JOptionPane.showMessageDialog(this, "La maquila ya esta en la hoja de especificacion");

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(frminventario.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (material == 0) {
                    // como si existe el material en la bd de datos de inventario, procedemos a integrarlo a Calzado
                    if (txtPrecio.getText().length() == 0) {
                        JOptionPane.showMessageDialog(this, "Falta agregar el Precio de la maquila");
                    } else {
                        //Asignamos variables a la especificacion
                        String Linea = txtLinea.getText().toUpperCase();
                        String Modelo = txtModelo.getText().toUpperCase();
                        String Articulo = txtArticulo.getText().toUpperCase();
                        String Color = txtColor.getText().toUpperCase();
                        String Nombre = txtMaquila.getText();
                        String Precio = txtPrecio.getText();
                        String Codigo = null;
                        String Pieza = null;
                        String Activo = "1";
                        //Asignamos el precio como resultado
                        String txtResultado = Precio;
                        // verificamos si esta seleccionado
                        if (!chkActivo.isSelected()) {
                            Activo = "0";
                        }
                        String sql = "SELECT * FROM maquila WHERE nombre='" + txtMaquila.getText() + "'";

                        //buscamos en la base de datos Maquila las especificaciones faltantes
                        try {
                            Statement completar;
                            completar = cn.createStatement();
                            ResultSet rs = completar.executeQuery(sql);
                            while (rs.next()) {
                                Codigo = rs.getString("codigo");
                                Pieza = rs.getString("pieza");
                            }
                        } catch (SQLException ex) {
                            System.out.println("Sin poder ejecutar el query para asignar valores de maquila");
                        }

                        //ya teniendo todos los valores integramos la especificacion a la BD calzado
                        try {
                            Statement stmt = cn.createStatement();
                            String grabar = "INSERT INTO calzado (modelo,codigo,linea,articulo,color,pieza,nombre,precio,resultado,estado,proceso) "
                                    + "VALUES ('"
                                    + Modelo + "','"
                                    + Codigo + "','"
                                    + Linea + "','"
                                    + Articulo + "','"
                                    + Color + "','"
                                    + Pieza + "','"
                                    + Nombre + "','"
                                    + Precio + "','"
                                    + txtResultado + "','"
                                    + Activo + "','manipulacion');";
                            stmt.executeUpdate(grabar);

                            stmt.close();
                            txtSubManipulacion.setText("0.00");
                            mostrarTabla();
                        } catch (SQLException ex) {
                            Logger.getLogger(frminventario.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                    
                }
            }if (contador == 0) {
                        JOptionPane.showMessageDialog(this, "No modifiques la ventana de maquila");
                        txtPredecible.setText("");
                        txtPar.setText("");
                        txtPrecio.setText("");
                    }
            
            
            // ********** Termina captura de maquila
        }
    }//GEN-LAST:event_btnIntegrarActionPerformed

    public void mostrarTabla() {
        String sql = "SELECT * FROM CALZADO where modelo='" + txtModelo.getText() + "' AND proceso='manipulacion' AND articulo='"
                + txtArticulo.getText() + "'";
        String[] cabecera = {"Codigo", "Pieza", "Nombre", "Medida", "Consumo", "Precio", "total"};
        // se definen los registros que llevara la tabla
        String[] registros = new String[7];
        // se hace el llamado sql de todos los usuarios

        System.out.println(sql);
        //establecemos los anchos en pixeles de las columnas
        int[] anchos = {80, 250, 700, 80, 80, 80, 80};
        manipulacion = new DefaultTableModel(null, cabecera);

        try {

            Statement tablaManipulacion;
            tablaManipulacion = cn.createStatement();
            ResultSet rs = tablaManipulacion.executeQuery(sql);
            while (rs.next()) {

                registros[0] = rs.getString("codigo");
                registros[1] = rs.getString("pieza");
                registros[2] = rs.getString("nombre");
                registros[3] = rs.getString("medida");
                registros[4] = rs.getString("consumo");
                registros[5] = rs.getString("precio");
                registros[6] = rs.getString("resultado");

                manipulacion.addRow(registros);
                // calculamos el subtotal de Manipulacion
                Double subtotal = Double.parseDouble(txtSubManipulacion.getText());
                Double agregar = Double.parseDouble(rs.getString("resultado"));
                Double resultado = subtotal + agregar;
                BigDecimal SubTotal = BigDecimal.valueOf(resultado);
                SubTotal = SubTotal.setScale(2, RoundingMode.HALF_UP);
                txtSubManipulacion.setText(String.valueOf(SubTotal));
            }
            tablaMan.setModel(manipulacion);
            for (int i = 0; i < cabecera.length; i++) {
                tablaMan.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                tablaMan.setFont(new java.awt.Font("Tahoma", 0, 12));
                txtPredecible.setText("");
                txtPar.setText("");
                txtPrecio.setText("");
            }

        } catch (SQLException ex) {
            System.out.println("Sin poder ejecutar el query a la tabla");
        }

    }

    public String redondeo() {
        Double par = Double.parseDouble(txtPar.getText());
        Double precio = Double.parseDouble(txtPrecio.getText());
        Double Resultado = par * precio;
        BigDecimal resultado = BigDecimal.valueOf(Resultado);
        resultado = resultado.setScale(2, RoundingMode.HALF_UP);
        String txtResultado = resultado.toString();
        return txtResultado;
    }
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        // verificamos que no esten los campos vacios
        if (txtLinea.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Escribe la linea del calzado");
        } else if (txtModelo.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Escribe el modelo del calzado");
        } else if (txtArticulo.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Escribe el articulo del calzado");
        } else if (txtColor.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Escribe el color del calzado");
        } else {

            //verificamos que el modelo no exista previamente
            int repetido = 0;
            try {
                String checar = "SELECT * FROM calzado WHERE articulo='" + txtArticulo.getText()
                        + "' and linea='" + txtLinea.getText() + "'";
                Statement verificar;
                verificar = cn.createStatement();
                ResultSet buscar = verificar.executeQuery(checar);
                while (buscar.next()) {
                    repetido++;
                    JOptionPane.showMessageDialog(null, "El articulo " + txtArticulo.getText()
                            + " ya existe\n en la linea " + txtLinea.getText(), "Alerta", 0);
                }
            } catch (Exception e) {
            }
            if (repetido == 0) {
                int respuesta = JOptionPane.showConfirmDialog(this, "se va a crear el siguiente calzado\nLinea:"
                        + txtLinea.getText() + "\nModelo: "
                        + txtModelo.getText() + "\nArticulo: "
                        + txtArticulo.getText() + "\n Color: "
                        + txtColor.getText(), "Confirmacion", 2);
                //verificamos que informacion se va a agregar y si lo acepta se integra a la BD
                if (respuesta == 0) {
                    //en caso que si, cancelamos los botones y activamos integrar
                    txtLinea.setEnabled(false);
                    txtModelo.setEnabled(false);
                    txtArticulo.setEnabled(false);
                    txtColor.setEnabled(false);
                    btnEditar.setEnabled(false);
                    btnCrear.setEnabled(false);
                    btnIntegrar.setEnabled(true);
                    btnImagen.setEnabled(true);
                    chkActivo.setEnabled(false);
                    txtSubManipulacion.setEnabled(false);
                    txtSubManipulacion.setText("0.00");
                } else {
                    //si se cancela la creacion de zapata dejamos limpio todo
                    txtLinea.setText("");
                    txtModelo.setText("");
                    txtArticulo.setText("");
                    txtColor.setText("");
                }
            }
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecio1ActionPerformed

    private void btnNuevaMaquilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaMaquilaActionPerformed
        maquila frm = new maquila();
        frm.setVisible(true);
        frm.setAlwaysOnTop(true);
    }//GEN-LAST:event_btnNuevaMaquilaActionPerformed

    private void btnActMaquilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActMaquilaActionPerformed
        //actualizamos Autocompletar maquila
        asignarAutocompletadoMaquila();
    }//GEN-LAST:event_btnActMaquilaActionPerformed

    private void btnActInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActInventarioActionPerformed
        //actualizamos autocompletar inventario
        asignarAutocompletado();
    }//GEN-LAST:event_btnActInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActInventario;
    private javax.swing.JButton btnActMaquila;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnIntegrar;
    private javax.swing.JButton btnNuevaMaquila;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JTable tablaMan;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMaquila;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPar;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecio1;
    private javax.swing.JTextField txtPredecible;
    private javax.swing.JTextField txtSubManipulacion;
    // End of variables declaration//GEN-END:variables
}
